[book]
title = "linuxliteracy"
authors = ["Laufeynumber1fan"]
description = "For cybersecurity students ONLY. Girls NOT allowed."
language = "en"
src = "src"

# Allow bash commands
[preprocessor.ocirun]
[[preprocessor.ocirun.langs]]
name = "bash"
image = "alpine/git"
command = ["bash", "source"]

[output.html]
smart-punctuation = true
mathjax-support = true
site-url = "/linuxliteracy/"
git-repository-url = "https://github.com/Laufeynumber1fan/linuxliteracy/tree/gh-pages"
hash-files = true

# This is enabled by default
[output.html.search]
enable = false

# Enable code blocks that start with "codelang,editable" to be editable by user
[output.html.playground]
editable = true

#Hide lines in codeblocks that start with whitespace + ~
[output.html.code.hidelines]
bash = "~"